variable "aws_region" {
  type        = string
  description = "The AWS region to deploy resources in"
  default     = "eu-central-1"
}

variable "bot_id" {
  type        = string
  description = "A unique identifier for this bot instance to allow multiple bots to run side-by-side in the same AWS account without collision (e.g. 'bot1', 'alice', 'bob')"
  default     = "bot1"
}

variable "telegram_bot_token" {
  type        = string
  description = "The Telegram Bot API token generated by @BotFather"
  sensitive   = true
}

variable "smerio_api_url" {
  type        = string
  description = "The base URL of the Smerio standalone application (e.g. http://budget.mywebsite.com)"
}

variable "smerio_telegram_token" {
  type        = string
  description = "The secret Telegram Token generated in the Smerio settings interface"
  sensitive   = true
}

variable "allowed_telegram_user_id" {
  type        = number
  description = "Strict numeric Telegram User ID of the single authorized sender (zero-trust)"
}

variable "llm_provider" {
  type        = string
  description = "The AI Model provider: 'gemini' (default), 'claude', or 'openai'"
  default     = "gemini"
  validation {
    condition     = contains(["gemini", "claude", "openai"], var.llm_provider)
    error_message = "The llm_provider must be one of: 'gemini', 'claude', 'openai'."
  }
}

variable "llm_api_key" {
  type        = string
  description = "The API key for the chosen LLM provider"
  sensitive   = true
}
